---

- name: ensure docker group present
  group:
    name: docker
    state: present
    system: true

- name: ensure docker user present
  user:
    append: true
    groups: docker
    state: present
    name: '{{ item }}'
  with_items: '{{ docker_users or [] }}'
