---

# handlers for ansible-role-docker
- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: true

- name: start docker
  service:
    name: docker
    state: started
    enabled: true

- name: reload docker
  service:
    name: docker
    state: reloaded
    enabled: true
